### PR TITLE
Adding uds connection support to remove the need for deprecated socke…

### PR DESCRIPTION
**Pull request by MahdiBM**
Sorry for the noises, didn't know renaming a branch will close its PR.

This is duplicate of https://github.com/vapor/postgres-nio/pull/301.

### The Problem

Connecting through sockets has been deprecated in recent changes, which limits the ability to use uds for connections.

### The Solution

This PR will add the ability to use uds using the new apis.

### More

to not cause confusion: I rebased the commits into 1 since some changes from first commits were reversed.

### CODE REVIEW

**Review by gwynne — APPROVED** [review]
LGTM again 🙂 @fabianfett?

**Comment by MahdiBM** [comment]
this last commit was stuck in Github client again due to the branch renaming i did. 
just adds the serverName back to the resolved connections.

**Comment by brucemontegani** [comment]
Can we get these changes reviewed please.

**Comment by fabianfett** [comment]
@MahdiBM Sorry, for taking so long to review this. I see the problem. However currently I'm not convinced that the approach taken, will serve us well into the future. 

Sadly I haven't come up with a better one, yet. However I'm on it!

**Comment by fabianfett** [comment]
Superseeded by #335.

**Pull request closed without merging**
