### PR TITLE
char(n) (BPCHAR) length fix

### LINKED ISSUE #71: assertion failure because internal typename for CHAR(n) is BPCHAR
I hit an assertion failure in `PostgresData+Int.swift`:

```swift
switch self.formatCode {
        case .binary:
            switch self.type {
            case .char, .bpchar:
                assert(value.readableBytes == 1) // <- Here
```

debugger output at that point:

```
(lldb) po self.type
▿ BPCHAR
  - rawValue : 1042

(lldb) po postgresData.debugDescription
"Optional(0x0020 (BPCHAR))"

(lldb) po self.debugDescription
"0x0020 (BPCHAR)"
```

and `value.readableBytes` is `2`.

Most likely has to do with CHAR(1) columns I have in my tables although those tables are empty when I hit the assertion.

### LINKED ISSUE #79: returns only one character from char(3) field
I have a table with a field of char(3) type. When I execute a query I got only one symbol instead all three characters. The data is ok in database, I see all three characters.

https://github.com/vapor/postgres-nio/blob/master/Sources/PostgresNIO/Data/PostgresData%2BString.swift#L50

For example, currency.column("id") - `"id": 0x594552 (BPCHAR)`.

### PR DESCRIPTION
**Pull request by tanner0101**
The `char(n)` (`BPCHAR`) data type now correctly supports values longer than one byte when converting to fixed-width integers or strings (fixes #71, fixes #79, #72).

### CODE REVIEW

**Comment by tkrajacic** [comment]
This now crashes in the PostgresDataDecoder.swift on

`return convertible.init(postgresData: data)! as! T`

with

`NIO-ELT-0-#0 (3): Fatal error: Unexpectedly found nil while unwrapping an Optional value`

**Comment by tanner0101** [comment]
@tkrajacic can you try `CHAR` instead of `CHARACTER`? 

From https://dba.stackexchange.com/questions/159090/how-to-store-one-byte-integer-in-postgresql

>  "char" is an "internal" type intended for simple and cheap enumeration.

**Comment by tkrajacic** [comment]
As it turns out, Postgres has no 1-byte type really, and even a `character(1)` uses 2 bytes.

See https://www.postgresql.org/docs/current/datatype-character.html
> The storage requirement for a short string (up to 126 bytes) is 1 byte plus the actual string, which includes the space padding in the case of character

There would be an internal type of `"CHAR"` (including the quotes) but this is not adhering to any standard
> The type "char" (note the quotes) is different from char(1) in that it only uses one byte of storage. It is internally used in the system catalogs as a simplistic enumeration type.

**Comment by tanner0101** [comment]
Merging this since it at least fixes #79. Solutions for Postgres' lack of a good "single byte" type can be discussed further.

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-beta.2.8](https://github.com/vapor/postgres-nio/releases/tag/1.0.0-beta.2.8)

**Pull request merged**
