### PR TITLE
Drop support for Swift 5.5

### PR DESCRIPTION
**Pull request by fabianfett**
### Motivation

@gwynne started to drop Swift 5.5 in #335. However a lot of code that we can remove now wasn't touched there. And it should not be touched in there. This PR removes all code that we can drop when requiring Swift 5.6.

### Changes

- Cleanup code after dropping 5.5

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
We can merge this after #335 once CI is updated

**Review by gwynne — APPROVED** [review]
LOL I already have about half of this done locally (including an update for the CI), let's get this merged and I'll rebase the UDS/Channel branch from that point.

**Comment by fabianfett** [comment]
nightly crashes the compiler... ignore.

**Comment by 0xTim** [comment]
Yeah this is being tracked at https://github.com/apple/swift/issues/65064

**Pull request merged**
