### PR TITLE
Follow up to fixing crash in queries that timeout

### PR DESCRIPTION
**Pull request by gwynne**
This hopefully solves the failed force-unwrap crash in the fix for #347 provided by #351.

cc @fabianfett @trasch

### CODE REVIEW

**Comment by trasch** [comment]
I can confirm that this fixes the remaining crash for me 👍

Thanks @gwynne and @fabianfett !

**Comment by fabianfett** [comment]
@trasch Do you have a repro for the crash?

**Comment by gwynne** [comment]
It fixes the proximate crash, but it's not really dealing with the actual underlying problem; I defer to @fabianfett for the real solution.

**Comment by trasch** [comment]
>  Do you have a repro for the crash?

@fabianfett Not publicly available, and it uses internal databases that aren't available externally.

What I'm doing is running a few million PostGIS queries with a connection pool of size 50, so lots of parallel queries with short timeouts.
I will try to create a test case that mimics this, but I will need some time. (And I hope that I didn't simply botch the connection pool...)

**Pull request closed without merging**
